FROM golang:1.24-alpine

# Install Air and other tools
RUN apk add --no-cache git curl && \
    curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

# Default command for dev
CMD ["air"]
