### Signup new user
POST {{host}}/signup
Content-Type: application/json

{
  "username": "rere",
  "email": "rer.sadouk@gmail.com",
  "password": "passwordthami"
}

### Login user
GET {{host}}/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "alicepassword"
}

> {%
    client.global.set("token", response.body.token);
%}

### Get list of users
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Get wallet details
GET {{host}}/wallet?address=0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511
Content-Type: application/json
Authorization: Bearer {{token}}

